const $ = (id) => document.getElementById(id);

const elements = {
  attachmentButton: $("attach-file"),
  attachments: $("attachments"),
  alwaysApproveToolsButton: $("always-approve-tools"),
  configFeedback: $("config-feedback"),
  configFields: $("config-fields"),
  configForm: $("config-form"),
  discard: $("discard"),
  interruptRunButton: $("interrupt-run"),
  messages: $("messages"),
  navButtons: Array.from(document.querySelectorAll("[data-page-target]")),
  pages: Array.from(document.querySelectorAll("[data-page]")),
  previewModal: $("preview-modal"),
  previewModalBody: $("preview-modal-body"),
  previewModalClose: $("preview-modal-close"),
  previewModalCopy: $("preview-modal-copy"),
  previewModalLabel: $("preview-modal-label"),
  previewModalMeta: $("preview-modal-meta"),
  previewModalSave: $("preview-modal-save"),
  previewModalTitle: $("preview-modal-title"),
  prompt: $("prompt"),
  saveConfigButton: $("save-config"),
  scrollToBottomButton: $("scroll-to-bottom"),
  send: $("send"),
  status: $("status"),
  blackboardApplyAll: $("blackboard-apply-all"),
  blackboardClear: $("blackboard-clear"),
  blackboardDismissAll: $("blackboard-dismiss-all"),
  blackboardEmpty: $("blackboard-empty"),
  blackboardLogin: $("blackboard-login"),
  blackboardMeta: $("blackboard-meta"),
  blackboardStatusText: $("blackboard-status-text"),
  blackboardSuggestionList: $("blackboard-suggestion-list"),
  blackboardSummary: $("blackboard-summary"),
  blackboardSync: $("blackboard-sync"),
  blackboardSyncFeedback: $("blackboard-sync-feedback"),
  todoClearAll: $("todo-clear-all"),
  todoClearCompleted: $("todo-clear-completed"),
  todoCreateForm: $("todo-create-form"),
  todoDetailInput: $("todo-detail-input"),
  todoDueInput: $("todo-due-input"),
  todoEmpty: $("todo-empty"),
  todoFeedback: $("todo-feedback"),
  todoFilterButtons: Array.from(document.querySelectorAll("[data-todo-filter]")),
  todoList: $("todo-list"),
  todoSearchInput: $("todo-search-input"),
  todoSortSelect: $("todo-sort-select"),
  todoTitleInput: $("todo-title-input"),
  todoUndoBar: $("todo-undo-bar"),
  todoUndoButton: $("todo-undo-button"),
  todoUndoText: $("todo-undo-text"),
  // Schedule elements
  scheduleCalendar: $("schedule-calendar"),
  scheduleCurrentMonth: $("schedule-current-month"),
  schedulePrev: $("schedule-prev"),
  scheduleNext: $("schedule-next"),
  scheduleCreateForm: $("schedule-create-form"),
  scheduleTitleInput: $("schedule-title-input"),
  scheduleStartInput: $("schedule-start-input"),
  scheduleEndInput: $("schedule-end-input"),
  scheduleDetailInput: $("schedule-detail-input"),
  scheduleToggleCreateButton: $("schedule-toggle-create"),
  scheduleFeedback: $("schedule-feedback"),
  scheduleList: $("schedule-list"),
};

export { $, elements };
